CLI and server bug fixes on Windows
pinecone-io/canopy pull request #170
Opened 2023-11-13 12:22 UTC by igiloh-pinecone

## Problem

Fixes multiple bugs when running the CLI on windows:
1. On windows, calling CLI commands that use the server (e.g. `canopy chat`) didn't work. 
2. There was also a bug in inferring the `/chat` endpoint, which was using `os.path.join()`
3. `canopy stop` tried to `pgrep gunicorn`, even though Windows doesn't have a `pgrep` command and Gunicorn isn't supported on windows.
4. The `/shutdown` endpoint wasn't working correctly on Windows

Resolves #166. 

## Solution

- The CLI used the url `http://0.0.0.0:8000`/ by default, which is not supported on windows. I replaced it with `http://localhost:8000`.
- In windows we need to send the `CTRL_C` signal, which has a totally different implementation than `SIGINT`

## Type of Change

- [X] Bug fix (non-breaking change which fixes an issue)

## Test Plan

Tested manually on mac, Windows and Linux.  
We need to add a proper CLI unit test (known issue)

2023-11-13 20:12 UTC, miararoy requested changes
small changes

2023-11-13 20:12 UTC, miararoy commented on src/canopy_cli/cli.py
> +            api_base=os.path.join(urljoin(chat_server_url, "/context")),
why we still need `os.path.join`

2023-11-13 20:12 UTC, miararoy commented on src/canopy_cli/cli.py
> +        "please use Docker"  # TODO: Add Docker instructions once we have a Dockerfile
extend here more, "for windows users, inline server experience is not stable, we recommend using docker"

2023-11-14 08:12 UTC, igiloh-pinecone commented on src/canopy_cli/cli.py
> +            api_base=os.path.join(urljoin(chat_server_url, "/context")),
We don't, that's a bug 🤦 .
FIxed

2023-11-14 08:43 UTC, miararoy approved these changes
lgtm

2023-11-14 10:43 UTC, merged