Add Anyscale Endpoint support and Llama Tokenizer
pinecone-io/canopy pull request #173
Opened 2023-11-14 23:05 UTC by kylehh

## Problem

Add Anyscale Endpoint support
Add Llama Tokenizer based on huggingface `tokenizers` library

## Solution

1. You can call Llama2 , Mistrial and Zephry models with Anyscale Endpoint
2. You can get tokenizer by Hugginface `tokenizers` libray

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan

Describe specific steps for validating this change.
1. Get your HF and Anyscale tokens and add them in the config/anyscale.yaml
2. `canopy start --config anyscale.yaml`

2023-11-15 14:38 UTC, igiloh-pinecone requested changes
@kylehh Thank you very much for your contribution!! This is highly appreciated!

Please see a few comments. The main 3 issues:
1. We plan to merge #171 today, which adds a `base_url` init argument to `OpenAILLM` class. With that change, the implementation of `AnyscaleLLM` could be as easy as inheriting `OpenAILLM` and passing hard coded `base_url` to `super().__init__()`.
2. The new classes, `AnyscaleLLM` and `LlamaTokenizer` require their own unit classes before this PR can be merged.
3. Let's figure out together if it's really required for every Canopy user to generate a HF identification token just for the Tokenizer, or can we find a more user friendly solution.

2023-11-15 14:38 UTC, igiloh-pinecone commented on src/canopy/utils/openai_exceptions.py
> +from importlib.metadata import version
This can be deleted, we're fixing the openai dependency in #171.  
We don't intend to be backwards supporting.

2023-11-16 23:52 UTC, kylehh commented on config/anyscale.yaml
> +      api_key: esecret_YOUR_ANYSCALE_TOKENS
removed

2023-11-16 23:53 UTC, kylehh commented on src/canopy/llm/anyscale.py
> +          You can set the "OPENAI_API_KEY" environment variable to your API key.
Done

2023-11-16 23:54 UTC, kylehh commented on src/canopy/tokenizer/llama.py
> +from tokenizers import Tokenizer
This is a great suggestion. Done

2023-11-17 00:21 UTC, kylehh commented on src/canopy/tokenizer/llama.py
update with transformers

2023-11-17 00:21 UTC, kylehh commented on src/canopy/tokenizer/llama.py
> +class LlamaTokenizer(BaseTokenizer):
added. But notice that llama tokenizer gives different result from openai

2023-11-17 00:22 UTC, kylehh commented on src/canopy/tokenizer/llama.py
> +        return "".join(tokens)
For the new tokenizer, I should just do "" instead of " " to pass the unit test

2023-11-17 00:23 UTC, kylehh commented on config/anyscale.yaml
> +    hf_token: hf_YOUR_HUGGINGFACE_TOKENS
hf_token is optional for model like `openlm-research/open_llama_7b_v2` 
So I didn't add the warning

2023-11-21 10:34 UTC, igiloh-pinecone commented on tests/system/llm/test_anyscale.py
Hi @kylehh, this seem to be a copy-paste of the OpenAILLM test file as-is.  
Can you please change this test file to be testing the actual `AnyscaleLLM` class?

2023-11-21 10:36 UTC, igiloh-pinecone commented on src/canopy/llm/anyscale.py
The linter tests on this branch still seem to be failing.  
Can you please run `flake8 .` and `mypy .` and fix any linter issues?

2023-11-26 09:48 UTC, igiloh-pinecone approved these changes
LGTM!

Thank you @kylehh for all of your efforts. Merging.

2023-11-27 11:53 UTC, merged