add JinaRecordEncoder
pinecone-io/canopy pull request #199
Opened 2023-12-05 10:54 UTC by JoanFM

## Problem

Depends on `pinecone-text` feature to add JinaEncoder. It aims to add JinaRecordEncoder class to allow users to use Jina Embeddings using Jina Embedding API https://jina.ai/embeddings/

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

2023-12-10 10:38 UTC, igiloh-pinecone requested changes
The only comment as about adding tests

2023-12-10 10:38 UTC, igiloh-pinecone commented on src/canopy/knowledge_base/record_encoder/jina.py
Hi @JoanFM , please also add a unit tests and a system tests.

Other than that LGTM!

2023-12-11 11:36 UTC, JoanFM commented on src/canopy/knowledge_base/record_encoder/jina.py
They have been added, please check again

2024-01-18 09:20 UTC, igiloh-pinecone approved these changes
LGTM!

2024-01-18 09:45 UTC, merged