Add `SentenceTransformersRecordEncoder`
pinecone-io/canopy pull request #263
Opened 2024-01-23 11:09 UTC by tomaarsen

Hello!

## Problem
This PR ports the `SentenceTransformerEncoder` from `pinecone_text` into `canopy`, allowing various Sentence Transformer models to be used. For example, most of [these models](https://huggingface.co/models?library=sentence-transformers) should now be usable.

## Solution

I based my work here on [`pinecone_text`](https://github.com/pinecone-io/pinecone-text) & the JinaRecordEncoder PR: #199.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan

You can attempt to run the tests to verify whether the default tiny `all-MiniLM-L6-v2` model can be used.

- Tom Aarsen

2024-01-23 12:27 UTC, tomaarsen commented
Hello!

First of all, I've ran flake8 and resolved the issues to satisfy your linter.

As for your comments: I think the benefit of a merger depends on whether you wish to use `pinecone-text` outside of the context of RAG or Canopy. I'm not very familiar with it, but it seems like a relatively light-weight library for Dense, Sparse and Hybrid embeddings that might see use elsewhere too. From my perspective, `pinecone-text` feels like a building block, and `canopy` an application putting that building block in an end-to-end application.

I think a merger means that you will end up only with an application, and users wouldn't quickly try and dig out the building block from the application for their own uses. That's just my suspicion though, and it's up to you all to decide whether that's even a problem anyways - I don't think `pinecone-text` had that big of an audience at this point after all.

That all said, the complexity is certainly lower if you merge everything. While they are two separate packages, you need to consider breaking changes between various combinations of versions of both projects, and you'll be more restricted as a result. If `canopy` becomes popular but `pinecone_text` does not, then it will be odd to ask users of the popular project to contribute to the lesser known project instead with extra e.g. embedding models.

And then there's also marketing considerations, which I'm not an expert on.

- Tom Aarsen

2024-01-24 10:03 UTC, tomaarsen commented
It looks like I should add `pinecone[dense]` as an extra to the `pyproject.toml` [here](https://github.com/pinecone-io/canopy/blob/6ba92c53a40ba4d9d3cec208eb36fdd46f4328f0/pyproject.toml#L41), so it'll be installed on the CI. What should I call the extra?

2024-01-24 14:58 UTC, igiloh-pinecone requested changes
@tomaarsen please see a few minor suggestions

2024-01-24 15:01 UTC, igiloh-pinecone commented
> It looks like I should add `pinecone[dense]` as an extra to the `pyproject.toml` [here](https://github.com/pinecone-io/canopy/blob/6ba92c53a40ba4d9d3cec208eb36fdd46f4328f0/pyproject.toml#L41), so it'll be installed on the CI. What should I call the extra?

@tomaarsen thanks for your efforts, and again a very good catch!  
I just opened https://github.com/pinecone-io/canopy/pull/266 which would address that need. You can assume it will be merged to `main` very soon.

2024-01-24 15:12 UTC, tomaarsen commented on src/canopy/knowledge_base/record_encoder/sentence_transformers.py
> +        encoder = SentenceTransformerEncoder(model_name, **kwargs)
Implemented via 2f821e4a61dfb5c5dc10129f0f500f202d06069d & 92d13e51484b75aa22a1eb3deaccdd1f847f9f76, let me know if you would like `model_name` to be renamed to `document_encoder_name`. Personally, I think `model_name` is more intuitive, but that's the phrasing that I'm familiar with.

2024-01-24 15:16 UTC, tomaarsen commented on tests/system/record_encoder/test_sentence_transformers_encoder.py
Skipped these tests in 81f21331eae2a80fa64925c88c17e15859b1fa87!

2024-01-24 16:25 UTC, igiloh-pinecone commented on src/canopy/knowledge_base/record_encoder/sentence_transformers.py
> +        encoder = SentenceTransformerEncoder(
We should probably wrap this in a `try`-`except` clause, and handle typical HF errors, re-raising with a clear and actionable error message.

2024-01-24 16:28 UTC, igiloh-pinecone commented on src/canopy/knowledge_base/record_encoder/sentence_transformers.py
> +        super().__init__(dense_encoder=encoder, batch_size=batch_size)
Please consider implementing the `_format_error(self, err)` method, which gets called if there was a runtime error at encoding time.  
We try to anticipate the typical misconfigurations, and re-raise these with a clear and actionable error message

2024-01-24 19:02 UTC, igiloh-pinecone commented on src/canopy/knowledge_base/record_encoder/sentence_transformers.py
> +        encoder = SentenceTransformerEncoder(model_name, **kwargs)
I agree that `model_name` is more intuitive. We'll consider a deeper renaming in the near future.  
Thanks!

2024-01-24 19:04 UTC, igiloh-pinecone commented
@tomaarsen thank you for your very quick response!  
Please see two comments about error handling (I added them a few minutes after publishing the official review). Other than that LGTM and I think we can approve and merge

2024-01-24 19:39 UTC, tomaarsen commented
I'll have a look at them tomorrow :)

- Tom Aarsen

2024-01-26 09:43 UTC, tomaarsen commented
Apologies for the delay. I've wrapped the __init__ in a try-except. To my knowledge, there are two common errors here: `ImportError` and `RepositoryNotFoundError`. `pinecone-text` already has a great actionable `ImportError` for the former, so I won't override that one. 

As for `_format_error(self, err)` - SentenceTransformers does not raise any specific errors for misconfigurations on runtime. It also does not have e.g. RateLimit exceptions and such, so I'm unsure what I could reasonably implement here.

Would you like additional changes?

- Tom Aarsen

2024-01-28 11:22 UTC, igiloh-pinecone commented
> Apologies for the delay. I've wrapped the `__init__` in a try-except. To my knowledge, there are two common errors here: `ImportError` and `RepositoryNotFoundError`. `pinecone-text` already has a great actionable `ImportError` for the former, so I won't override that one.

Actually we should probably wrap the `ImportError`  from `pinecone-text` asking users to install `pinecone-text[dense]` and replace it with a message to install `canopy-sdk[torch]` instead, right? (see https://github.com/pinecone-io/canopy/pull/266) 

> As for `_format_error(self, err)` - SentenceTransformers does not raise any specific errors for misconfigurations on runtime. It also does not have e.g. RateLimit exceptions and such, so I'm unsure what I could reasonably implement here.

I was thinking about stuff like catching OOM errors and asking user to change the `batch_size` config param, or other such cases where the actionable fix is related to Canopy's config.   
But if there aren't any (or they are not too obvious) - sure, let's keep it as is.

> Would you like additional changes?

No, thank you very much for your efforts!  
Approving the PR now

> Edit: How would you like me to counteract the mypy failure?

Given that it looks like a [known issue](https://github.com/huggingface/huggingface_hub/issues/1662), I guess there's not much we can do about it other than adding `'huggingface_hub.utils'` to mypy's override list in the `pyproject.toml` file.

2024-01-28 11:23 UTC, igiloh-pinecone approved these changes
LGTM!

2024-02-07 13:45 UTC, tomaarsen reviewed
A few comments on the recent changes :)

2024-02-07 13:45 UTC, tomaarsen commented on tests/system/record_encoder/test_sentence_transformers_encoder.py
> +    except ImportError as e:
```suggestion
    except ImportError:
```
`e` was unused, this should hopefully satisfy mypy.

2024-02-07 13:45 UTC, tomaarsen commented on tests/system/record_encoder/test_sentence_transformers_encoder.py
> +            f"tests"
```suggestion
            "`transformers` extra not installed. Skipping SentenceTransformer system "
            "tests"
```
The `f` prefix should not be used here

2024-02-07 13:45 UTC, tomaarsen commented on tests/unit/record_encoder/test_sentence_transformers_encoder.py
> +    except ImportError as e:
```suggestion
    except ImportError:
```
idem

2024-02-07 13:45 UTC, tomaarsen commented on tests/unit/record_encoder/test_sentence_transformers_encoder.py
> +            f"tests"
```suggestion
            "`transformers` extra not installed. Skipping SentenceTransformer unit "
            "tests"
```
idem

2024-02-07 13:45 UTC, tomaarsen commented on src/canopy/knowledge_base/record_encoder/sentence_transformers.py
> +            )
```suggestion
            ) from e
```
Satisfies mypy & correctly links the errors.

2024-02-07 16:51 UTC, merged