Small update library.md - add an encoder to the KB initialisation as an example
pinecone-io/canopy pull request #302
Opened 2024-02-20 16:39 UTC by coreation

## Problem

Solves [this issue](https://github.com/pinecone-io/canopy/issues/186) 

## Solution

n/a

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [x] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan

n/a

2024-02-21 09:01 UTC, izellevy requested changes

2024-02-21 09:05 UTC, coreation commented on docs/library.md
> +encoder = OpenAIRecordEncoder(model_name="text-embedding-3-small")
hey @izellevy thanks for the comment, do I understand it correctly to 
* undo the changes on the library.md file
* add the text you wrote to the "actual documentation"...is that the README.md file?

Or do you want me to keep the added lines, but add the OpenAIRecordEncoder to the imports?

2024-02-21 09:28 UTC, izellevy commented on docs/library.md
> +encoder = OpenAIRecordEncoder(model_name="text-embedding-3-small")
Hey @coreation sorry for the confusion. Inside the library.md file.

<OLD EXAMPLE> (init without the record encoder)

Alternatively, ....

<NEW EXAMPLE> (init with record encoder. Also we need to add the import OpenAIRecordEncoder)

2024-02-21 10:23 UTC, coreation commented on docs/library.md
> +encoder = OpenAIRecordEncoder(model_name="text-embedding-3-small")
Got it, so just make a new example with the init containing an explicitly defined record encoder, below the existing example, right?

2024-02-21 11:14 UTC, izellevy commented on docs/library.md
> +encoder = OpenAIRecordEncoder(model_name="text-embedding-3-small")
Exactly 👍

2024-02-26 12:40 UTC, izellevy commented on docs/library.md
> +encoder = OpenAIRecordEncoder(model_name="text-embedding-3-small")
@coreation any updates on that?

2024-02-28 16:30 UTC, coreation commented on docs/library.md
> +encoder = OpenAIRecordEncoder(model_name="text-embedding-3-small")
@izellevy done! Sorry for the delay for a small update, work/life is hectic at the moment :)

2024-02-29 14:12 UTC, merged